A project for ensuring that `https://` is used for everything except where it is not possible.

= Introduction

Today it is important for everything, https://www.troyhunt.com/heres-why-your-static-website-needs-https/[including static sites], to be over https.
It can be difficult to switch to `https://` and then to maintain using `https://`.
This project aims to help at both.

== Modules

The project is split up into the following modules:

* https://github.com/spring-io/nohttp/tree/master/nohttp[nohttp] - the core project that allows finding and replacing `http://` URLs
* https://github.com/spring-io/nohttp/tree/master/nohttp-cli[nohttp-cli] - a thin wrapper around `nohttp` that allows running it from the command line
* https://github.com/spring-io/nohttp/tree/master/nohttp-checkstyle[nohttp-checkstyle] - provides https://checkstyle.org/[checkstyle] integration with nohttp
* https://github.com/spring-io/nohttp/tree/master/nohttp-gradle[nohttp-gradle] - provides https://gradle.org[Gradle] integration with nohttp
* https://github.com/spring-io/nohttp/tree/master/samples[samples] - provides samples of using nohttp

== FAQ

*How can I automate fixing my existing code?* 

Automation is beyond the scope of this project. However, you can easily automate fixing your existing code by scripting along with https://github.com/spring-io/nohttp/tree/master/nohttp-cli[nohttp-cli]. If you use GitHub, you can leverage https://developer.github.com/v3/[GitHub APIs] to automatically clone repositories within a set of organizations. You can use https://github.com/github/hub[hub] to automate sending Pull Requests.
