= NoHttpPlugin
:toc:

Applies <<NoHttpCheckstylePlugin>> and <<NoHttpCliPlugin>>

== Sample

You can find a working sample at https://github.com/spring-io/nohttp/tree/main/samples/nohttp-gradle-sample[nohttp-gradle-sample].

== Usage

In its simplest form, you just need to add the Plugin to the root project of your build. You can optionally configure it using `nohttp`.

For example in Groovy:

`build.gradle`
[source,groovy]
----
plugins {
	id "io.spring.nohttp" version "0.0.10"
}

nohttp {
	...
}
----

Or in Kotlin:

`build.gradle.kts`
[source,kotlin]
----
plugins {
	id("io.spring.nohttp") version "0.0.10"
}

nohttp {
	...
}
----

== NoHttpCheckstylePlugin

Configures Gradle's https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.Checkstyle.html[Checkstyle] task to integrate with https://github.com/spring-io/nohttp/tree/main/nohttp-checkstyle[nohttp-checkstyle] to verify there are no restricted usages of `http://`.

The plugin only needs to be added to the root project as all subdirectories are checked.


=== Tasks

The `NoHttpCheckstylePlugin` adds the following tasks to the project:

`checkstyleNohttp` — https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.Checkstyle.html[Checkstyle]::
_Depends on_: `classes`
+
Runs Checkstyle to verify no restricted uses of `http://`.

==== Dependencies added to other tasks

The `NoHttpCheckstylePlugin` adds the following dependencies to tasks.

`check`::
_Depends on_: `checkstyleNohttp`.

=== Project layout

By default, the `NoHttpCheckstylePlugin` expects configuration files to be placed in the root project, but this can be changed.

----
<root>
└── config
    └── nohttp                 // <1>
        └── checkstyle.xml     // <2>
        └── suppressions.xml   // <3>
        └── allowlist.lines    // <4>
----
<1> Nohttp configuration files go here
<2> A custom checkstyle.xml file to use for `checkstyleNohttp`. The default can be found in the https://github.com/spring-io/nohttp/blob/main/nohttp-checkstyle/README.adoc#configuration[nohttp-checkstyle documentation]
<3> A suppressions file to use for `checkstyleNohttp`. The default is no suppressions
<4> https://github.com/spring-io/nohttp/tree/main/nohttp-checkstyle#custom-allowlist[Custom allowlist] to use

=== Dependency management

The nohttp plugin adds the following dependency configurations:

.nohttp plugin - dependency configurations
[cols="a,a", options="header"]
|===
| Name
| Meaning

| `nohttp`
| The nohttp libraries to use. The default is the same version of nohttp as the Nohttp Gradle Plugin.
|===


=== Configuration

The https://github.com/spring-io/nohttp/blob/main/nohttp-gradle/src/main/java/io/spring/nohttp/gradle/NoHttpExtension.java[NohttpExtension] is used to customize the configuration. An example configuration is:

[source,groovy]
----
nohttp {
    allowlistFile = project.file('src/nohttp/allowlist.lines') <1>
    source.exclude "**/test-output/**"                         <2>
    toolVersion = '0.0.1.BUILD-SNAPSHOT'                       <3>
}
----

<1> `allowlistFile` (https://docs.oracle.com/javase/8/docs/api/java/io/File.html[File]) - instructs nohttp to use `src/nohttp/allowlist.lines` to provide https://github.com/spring-io/nohttp/tree/main/nohttp#regexpredicatecreateallowlistinputstream[Custom Rules] for allowing HTTP URLs. Modifying the `allowlistFile` also modifies the default <<project-layout>> to look for the other configuration in the parent directory of `allowlistFile` (i.e. `src/nohttp`) as apposed to `config/nohttp`. This means if you have a file named `checkstyle.xml` in the same folder as `allowlistFile` you either need to include https://github.com/spring-io/nohttp/tree/master/nohttp-checkstyle#nohttpcheck[NoHttpCheck] in the file or you need to explicitly <<Configuring nohttpCheckstyle,configure nohttpCheckstyle task>> with a https://github.com/spring-io/nohttp/tree/master/nohttp-checkstyle#configuration[different checkstyle file].
<2> `source` (https://docs.gradle.org/current/userguide/working_with_files.html#sec:file_trees[FileTree]) - instructs nohttp what files to include / exclude. In this example, we exclude anything in the folder `test-output`.
<3> `toolVersion` - Updates the version of nohttp to use. The default is the same version as the nohttp Gradle Plugin version being used.

==== Configuring nohttpCheckstyle

You can also configure `nohttpCheckstyle` https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.Checkstyle.html[Checkstyle task] directly.

=== Built-in variables

The `NoHttpCheckstylePlugin` defines:

- `config_loc` property that can be used in Checkstyle configuration files to define paths to other configuration files like `suppressions.xml`.
- `nohttp.checkstyle.allowlistFileName` property that can be used in Checkstyle configuration files to define paths to other configuration files like `suppressions.xml`.

== NoHttpCliPlugin

Adds a https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/JavaExec.html[JavaExec] task that allows running https://github.com/spring-io/nohttp/tree/main/nohttp-cli[nohttp-cli].

=== Tasks

The Application plugin adds the following tasks to the project.

`nohttp` — https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/JavaExec.html[JavaExec]::
+
Runs https://github.com/spring-io/nohttp/tree/main/nohttp-cli[nohttp-cli] against the project.

=== nohttp samples

Run with the defaults. It finds all restricted usages of `http://` and reports them.

----
./gradlew nohttp
----

Outputs the help

----
./gradlew nohttp --args='--help'
----

Advanced sample

----
./gradlew nohttp --args='-D=build -D=.git -F=spring.schemas -w config/nohttp/allowlist.lines'
----

- Exclude the folders 'build', `.git'
- Exclude the files 'spring.schemas`
- Use additional `allowlistFile` to provide https://github.com/spring-io/nohttp/tree/main/nohttp#regexpredicatecreateallowlistinputstream[Custom Rules] of `config/nohttp/allowlist.lines`
